### ISSUE TITLE
슬라이더 및 각종 기능 비활성화

### ISSUE THREAD

**Issue by Ras034** [n7484443/cyoap_vue#4]
https://neway.neocities.org/Reincarnated/

슬라이더 - 비활성화
배경 이미지 - 비활성화 

프로그램 상과 웹상 전후 비교 

![image](https://github.com/user-attachments/assets/26700a06-26fc-456f-86c2-35dca55aa772)
![image](https://github.com/user-attachments/assets/5fed3eb1-ca6e-4081-958b-9de72d155c75)

추가 - vue의 웹상에서도 다크모드 표기가 가능하도록 설정 가능했으면 함.

**Comment by n7484443** [comment]
[v4.2.5](https://github.com/n7484443/cyoap_vue/releases/tag/v4.2.5) 에서 수정 완료.
