### ISSUE TITLE
기존 오류 잔존 및 개선 요청

### ISSUE THREAD

**Issue by Ras034** [n7484443/cyoap_vue#5]
![image](https://github.com/user-attachments/assets/33c9a0be-9b11-4b87-aaf3-095144ba1d38)

배경 이미지 미인식 문제가 남아있으며
미묘하게 프로그램 레이아웃과 차이나는 부분이 개선되었으면 합니다.

**Comment by Ras034** [comment]
선택지에 공간을 만들기 위해 스페이스나 엔터를 통해 빈 공간을 만드는 경우가 있는데 
이 때 웹상에서 엔더, 스페이스만 있는 줄이 아에 생략되거나 사라지는 경우가 있습니다.
이를 해결하기 위한 방법이 있다면 알려주실 수 있을까요?

**Comment by n7484443** [comment]
[v4.2.7](https://github.com/n7484443/cyoap_vue/releases/tag/v4.2.7) 에서 이미지 주소 관련 버그는 고쳤습니다.
빈 공간에 대한 문제는 quill 포맷을 html로 바꿔주는 라이브러리가 너무 노후화되어 타 라이브러리로 교체해야 하여, 아마도 시간이 약간 걸릴 듯 합니다.

**Comment by n7484443** [comment]
[v4.2.8](https://github.com/n7484443/cyoap_vue/releases/tag/v4.2.8) 타 라이브러리로 교체 완료.
아마 이제 정상적으로 작동할겁니다.
