### ISSUE TITLE
배경 이미지 오류 잔존

### ISSUE THREAD

**Issue by Ras034** [n7484443/cyoap_vue#6]
4.2.7, 4.2.9 버전 모두 배경 이미지가 안보이는 현상이 존재합니다.

**Comment by Ras034** [comment]
확인 결과 이미지를

dist/images/ 에서 불러와야하는데

assets/dist/images/
에서 불러오려고 하고있습니다.

**Comment by Ras034** [comment]
확인 결과 
assets 위치에
dist/images 폴더를 만들어준 후 이미지 파일 삽입시 정상작동되었습니다.

**Comment by n7484443** [comment]
v4.3.0에서 이번엔 진짜로 수정하였습니다.
